import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { getServerSession } from "next-auth";
import { authConfig } from "@/lib/auth";
import Providers from "@/app/providers";
import AuthButtons from "@/components/auth-buttons";
import CommandPalette from "@/components/command-palette";
import Toaster from "@/components/ui/toaster";
import { Input } from "@/components/ui/input";
// icons moved to SidebarNav via string mapping; no direct imports here
import SidebarNav from "@/components/sidebar-nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authConfig as any);
  return (
    <html lang="tr">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="min-h-screen">
          <div className="flex">
            <aside className="sticky top-0 h-screen w-64 shrink-0 border-r border-[var(--border)] bg-white shadow-sm">
              <div className="flex h-14 items-center justify-between px-4">
                <Link href="/" className="flex items-center gap-2">
                  <span className="inline-block h-5 w-5 rounded bg-gradient-to-b from-blue-600 to-blue-500 dark:from-blue-400 dark:to-blue-300" />
                  <div className="leading-tight">
                    <div className="text-sm font-bold">BUMM</div>
                    <div className="text-[11px] text-blue-700 dark:text-blue-300">Buski Migration Manager</div>
                  </div>
                </Link>
              </div>
              <nav className="space-y-6 px-3 py-2 text-sm">
                <div>
                  <div className="px-2 text-xs font-semibold text-zinc-500">Dashboards</div>
                  <SidebarNav items={[{ href: "/", label: "Default", icon: "home", exact: true }]} />
                </div>
                <div>
                  <div className="px-2 text-xs font-semibold text-zinc-500">Apps</div>
                  <SidebarNav
                    items={[
                      { href: "/projects", label: "Projeler", icon: "folder-kanban" },
                      { href: "/tasks", label: "Görevler", icon: "list-todo" },
                      { href: "/kanban", label: "Kanban", icon: "folder-kanban" },
                      { href: "/notes", label: "Notlar", icon: "notebook-pen" },
                      { href: "/calendar", label: "Takvim", icon: "calendar" },
                      { href: "/calendar-copy", label: "Takvim (Klon)", icon: "calendar" },
                      { href: "/teams", label: "Takımlar", icon: "users" },
                      { href: "/people", label: "Kişiler", icon: "users" },
                    ]}
                  />
                </div>
                
              </nav>
            </aside>
            <div className="flex-1">
              <header className="sticky top-0 z-10 border-b border-[var(--border)] bg-white/90 backdrop-blur supports-[backdrop-filter]:bg-white/80">
                <div className="flex items-center justify-between px-2 sm:px-4 lg:px-6 py-3">
                  <div className="flex items-center gap-2">
                    <Input placeholder="Ara" className="w-80" />
                  </div>
                  <div className="flex items-center gap-3">
                    <CommandPalette />
                    <AuthButtons session={session} />
                  </div>
                </div>
              </header>
              <main className="px-2 sm:px-4 lg:px-6 py-4 space-y-6 overflow-x-hidden">
                <Providers>{children}</Providers>
              </main>
            </div>
          </div>
        </div>
        <Toaster richColors closeButton />
      </body>
    </html>
  );
}
