import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { getServerSession } from "next-auth";
import { authConfig } from "@/lib/auth";
import Providers from "@/app/providers";
import AuthButtons from "@/components/auth-buttons";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authConfig as any);
  return (
    <html lang="tr">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="border-b bg-white">
          <nav className="mx-auto flex max-w-6xl items-center justify-between px-6 py-3">
            <div className="flex items-center gap-6">
              <Link href="/dashboard" className="font-medium">Dashboard</Link>
              <Link href="/projects" className="font-medium">Projeler</Link>
              <Link href="/calendar" className="font-medium">Takvim</Link>
            </div>
            <AuthButtons session={session} />
          </nav>
        </header>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
